### ISSUE TITLE
Firewall configs copyright notice

### ISSUE THREAD

**Issue by diekmann** [secgroup/fws#2]
Hey,

cool work, thanks for promoting the real world firewall configs :grin: 
I tried hard to collect them -- if possible -- with the most permissive license, please try to [ShareAlike](https://creativecommons.org/licenses/by-nc-sa/3.0/) :wink:

TODO: Please add license notes to fws/examples/real-world/ to allow all researches to use this data :smile: 

Thanks for mirroring! Keep on making firewall configs better :+1:

**Comment by wert310** [comment]
Hi!
We added the license notes in the `README.org` file and included the ShareAlike `LICENSE` file.

Thank you very much for the awesome collection of configs! :+1:

**Comment by diekmann** [comment]
By the way, do you want to become collaborator for github.com/diekmann/net-network? A central place to dump such configs would be nice.
